// <auto-generated />
namespace OrangeApartments.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_auth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_auth));
        
        string IMigrationMetadata.Id
        {
            get { return "201709040931458_initial_auth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
